name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build and push Docker image
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          docker_username: ${{ secrets.docker_username }}
          docker_pwd: ${{ secrets.docker_pwd }}
        run: |
          docker login -u $docker_username -p $docker_pwd
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 244530008913.dkr.ecr.eu-west-1.amazonaws.com
          rev=$(git rev-parse --short HEAD)
          docker build . -t remote-docker-tag
          docker tag build-docker-container-tag daskelars/remote-docker-tag
          docker tag remote-docker-tag 244530008913.dkr.ecr.eu-west-1.amazonaws.com/ecr-repo:$rev
          docker push daskelars/remote-docker-tag
          docker push 244530008913.dkr.ecr.eu-west-1.amazonaws.com/ecr-repo:$rev
